/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TimesheetEntry {
    id: string;
    status: TimesheetStatus;
    resourceId: string;
    date: Time;
    description: string;
    projectId: string;
    hoursLogged: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Milestone {
    id: string;
    title: string;
    completed: boolean;
    dueDate: Time;
}
export interface Resource {
    id: string;
    doj: Time;
    status: ResourceStatus;
    client: string;
    assignmentStartDate: Time;
    totalExperience: string;
    name: string;
    role: string;
    skillTags: Array<string>;
    projectManager: string;
    deliveryHead: string;
    assignmentEndDate: Time;
    email: string;
    employeeId: string;
    projectId?: string;
    practice: string;
    primarySkills: Array<string>;
    billabilityStatus: BillabilityStatus;
    contactNumber: string;
    department: string;
    secondarySkills: Array<string>;
    location: string;
    nonBillableStatus?: NonBillableStatus;
    project: string;
    reportingManager: string;
}
export interface Project {
    id: string;
    status: ProjectStatus;
    assignedResourceIds: Array<string>;
    endDate: Time;
    name: string;
    description: string;
    budget: bigint;
    startDate: Time;
    milestones: Array<Milestone>;
    managerName: string;
}
export interface UserProfile {
    appRole: UserRole;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BillabilityStatus {
    billable = "billable",
    nonBillable = "nonBillable"
}
export enum NonBillableStatus {
    availableForDeployment = "availableForDeployment",
    solutionInvestment = "solutionInvestment",
    biBench = "biBench",
    partialBench = "partialBench",
    projectBuffer = "projectBuffer",
    benchBlocked = "benchBlocked",
    maternity = "maternity",
    deliverySupport = "deliverySupport"
}
export enum ProjectStatus {
    active = "active",
    completed = "completed",
    onHold = "onHold",
    planning = "planning"
}
export enum ResourceStatus {
    active = "active",
    inactive = "inactive"
}
export enum TimesheetStatus {
    submitted = "submitted",
    approved = "approved",
    draft = "draft"
}
export enum UserRole {
    pm = "pm",
    pmo = "pmo",
    admin = "admin",
    deliveryHead = "deliveryHead",
    employee = "employee",
    management = "management"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Bulk-add projects. Permitted for admins and PMO users.
     */
    addBulkProjects(projectList: Array<Project>): Promise<void>;
    /**
     * / Bulk-add resources. Permitted for admins and PMO users.
     */
    addBulkResources(resourceList: Array<Resource>): Promise<void>;
    /**
     * / Create a new project. Permitted for admins and PMO users.
     */
    addProject(project: Project): Promise<void>;
    /**
     * / Add a single resource. Permitted for admins and PMO users.
     */
    addResource(resource: Resource): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    /**
     * / **************** Power BI Reporting ************
     */
    getPowerBIEmbedUrl(): Promise<string | null>;
    /**
     * / **************** Projects **********************
     */
    getProjects(status: ProjectStatus | null, managerName: string | null, startDate: Time | null, endDate: Time | null): Promise<Array<Project>>;
    /**
     * / **************** Resource Management ********************
     */
    getResources(): Promise<Array<Resource>>;
    /**
     * / **************** Timesheets *******************
     */
    getTimesheetEntries(resourceId: string | null, projectId: string | null, startDate: Time | null, endDate: Time | null): Promise<Array<TimesheetEntry>>;
    /**
     * / **************** User Profiles *****************
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setPowerBIEmbedUrl(url: string): Promise<void>;
    /**
     * / Update an existing project. Permitted for admins and PMO users.
     */
    updateProject(project: Project): Promise<void>;
}
import type { BillabilityStatus as _BillabilityStatus, Milestone as _Milestone, NonBillableStatus as _NonBillableStatus, Project as _Project, ProjectStatus as _ProjectStatus, Resource as _Resource, ResourceStatus as _ResourceStatus, Time as _Time, TimesheetEntry as _TimesheetEntry, TimesheetStatus as _TimesheetStatus, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBulkProjects(arg0: Array<Project>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkProjects(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkProjects(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBulkResources(arg0: Array<Resource>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkResources(to_candid_vec_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkResources(to_candid_vec_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(to_candid_Project_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(to_candid_Project_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addResource(arg0: Resource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(to_candid_Resource_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(to_candid_Resource_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPowerBIEmbedUrl(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPowerBIEmbedUrl();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPowerBIEmbedUrl();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(arg0: ProjectStatus | null, arg1: string | null, arg2: Time | null, arg3: Time | null): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResources();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResources();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimesheetEntries(arg0: string | null, arg1: string | null, arg2: Time | null, arg3: Time | null): Promise<Array<TimesheetEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimesheetEntries(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimesheetEntries(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPowerBIEmbedUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPowerBIEmbedUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPowerBIEmbedUrl(arg0);
            return result;
        }
    }
    async updateProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(to_candid_Project_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(to_candid_Project_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BillabilityStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillabilityStatus): BillabilityStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_NonBillableStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NonBillableStatus): NonBillableStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceStatus): ResourceStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_TimesheetEntry_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimesheetEntry): TimesheetEntry {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_TimesheetStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimesheetStatus): TimesheetStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NonBillableStatus]): NonBillableStatus | null {
    return value.length === 0 ? null : from_candid_NonBillableStatus_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: _UserRole;
    name: string;
}): {
    appRole: UserRole;
    name: string;
} {
    return {
        appRole: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.appRole),
        name: value.name
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ProjectStatus;
    assignedResourceIds: Array<string>;
    endDate: _Time;
    name: string;
    description: string;
    budget: bigint;
    startDate: _Time;
    milestones: Array<_Milestone>;
    managerName: string;
}): {
    id: string;
    status: ProjectStatus;
    assignedResourceIds: Array<string>;
    endDate: Time;
    name: string;
    description: string;
    budget: bigint;
    startDate: Time;
    milestones: Array<Milestone>;
    managerName: string;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n38(_uploadFile, _downloadFile, value.status),
        assignedResourceIds: value.assignedResourceIds,
        endDate: value.endDate,
        name: value.name,
        description: value.description,
        budget: value.budget,
        startDate: value.startDate,
        milestones: value.milestones,
        managerName: value.managerName
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    doj: _Time;
    status: _ResourceStatus;
    client: string;
    assignmentStartDate: _Time;
    totalExperience: string;
    name: string;
    role: string;
    skillTags: Array<string>;
    projectManager: string;
    deliveryHead: string;
    assignmentEndDate: _Time;
    email: string;
    employeeId: string;
    projectId: [] | [string];
    practice: string;
    primarySkills: Array<string>;
    billabilityStatus: _BillabilityStatus;
    contactNumber: string;
    department: string;
    secondarySkills: Array<string>;
    location: string;
    nonBillableStatus: [] | [_NonBillableStatus];
    project: string;
    reportingManager: string;
}): {
    id: string;
    doj: Time;
    status: ResourceStatus;
    client: string;
    assignmentStartDate: Time;
    totalExperience: string;
    name: string;
    role: string;
    skillTags: Array<string>;
    projectManager: string;
    deliveryHead: string;
    assignmentEndDate: Time;
    email: string;
    employeeId: string;
    projectId?: string;
    practice: string;
    primarySkills: Array<string>;
    billabilityStatus: BillabilityStatus;
    contactNumber: string;
    department: string;
    secondarySkills: Array<string>;
    location: string;
    nonBillableStatus?: NonBillableStatus;
    project: string;
    reportingManager: string;
} {
    return {
        id: value.id,
        doj: value.doj,
        status: from_candid_ResourceStatus_n43(_uploadFile, _downloadFile, value.status),
        client: value.client,
        assignmentStartDate: value.assignmentStartDate,
        totalExperience: value.totalExperience,
        name: value.name,
        role: value.role,
        skillTags: value.skillTags,
        projectManager: value.projectManager,
        deliveryHead: value.deliveryHead,
        assignmentEndDate: value.assignmentEndDate,
        email: value.email,
        employeeId: value.employeeId,
        projectId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.projectId)),
        practice: value.practice,
        primarySkills: value.primarySkills,
        billabilityStatus: from_candid_BillabilityStatus_n45(_uploadFile, _downloadFile, value.billabilityStatus),
        contactNumber: value.contactNumber,
        department: value.department,
        secondarySkills: value.secondarySkills,
        location: value.location,
        nonBillableStatus: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.nonBillableStatus)),
        project: value.project,
        reportingManager: value.reportingManager
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TimesheetStatus;
    resourceId: string;
    date: _Time;
    description: string;
    projectId: string;
    hoursLogged: bigint;
}): {
    id: string;
    status: TimesheetStatus;
    resourceId: string;
    date: Time;
    description: string;
    projectId: string;
    hoursLogged: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TimesheetStatus_n53(_uploadFile, _downloadFile, value.status),
        resourceId: value.resourceId,
        date: value.date,
        description: value.description,
        projectId: value.projectId,
        hoursLogged: value.hoursLogged
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pm: null;
} | {
    pmo: null;
} | {
    admin: null;
} | {
    deliveryHead: null;
} | {
    employee: null;
} | {
    management: null;
}): UserRole {
    return "pm" in value ? UserRole.pm : "pmo" in value ? UserRole.pmo : "admin" in value ? UserRole.admin : "deliveryHead" in value ? UserRole.deliveryHead : "employee" in value ? UserRole.employee : "management" in value ? UserRole.management : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    onHold: null;
} | {
    planning: null;
}): ProjectStatus {
    return "active" in value ? ProjectStatus.active : "completed" in value ? ProjectStatus.completed : "onHold" in value ? ProjectStatus.onHold : "planning" in value ? ProjectStatus.planning : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): ResourceStatus {
    return "active" in value ? ResourceStatus.active : "inactive" in value ? ResourceStatus.inactive : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    billable: null;
} | {
    nonBillable: null;
}): BillabilityStatus {
    return "billable" in value ? BillabilityStatus.billable : "nonBillable" in value ? BillabilityStatus.nonBillable : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    availableForDeployment: null;
} | {
    solutionInvestment: null;
} | {
    biBench: null;
} | {
    partialBench: null;
} | {
    projectBuffer: null;
} | {
    benchBlocked: null;
} | {
    maternity: null;
} | {
    deliverySupport: null;
}): NonBillableStatus {
    return "availableForDeployment" in value ? NonBillableStatus.availableForDeployment : "solutionInvestment" in value ? NonBillableStatus.solutionInvestment : "biBench" in value ? NonBillableStatus.biBench : "partialBench" in value ? NonBillableStatus.partialBench : "projectBuffer" in value ? NonBillableStatus.projectBuffer : "benchBlocked" in value ? NonBillableStatus.benchBlocked : "maternity" in value ? NonBillableStatus.maternity : "deliverySupport" in value ? NonBillableStatus.deliverySupport : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    approved: null;
} | {
    draft: null;
}): TimesheetStatus {
    return "submitted" in value ? TimesheetStatus.submitted : "approved" in value ? TimesheetStatus.approved : "draft" in value ? TimesheetStatus.draft : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimesheetEntry>): Array<TimesheetEntry> {
    return value.map((x)=>from_candid_TimesheetEntry_n51(_uploadFile, _downloadFile, x));
}
function to_candid_BillabilityStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillabilityStatus): _BillabilityStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_NonBillableStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NonBillableStatus): _NonBillableStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceStatus): _ResourceStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Resource_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Resource): _Resource {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus | null): [] | [_ProjectStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ProjectStatus_n11(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: ProjectStatus;
    assignedResourceIds: Array<string>;
    endDate: Time;
    name: string;
    description: string;
    budget: bigint;
    startDate: Time;
    milestones: Array<Milestone>;
    managerName: string;
}): {
    id: string;
    status: _ProjectStatus;
    assignedResourceIds: Array<string>;
    endDate: _Time;
    name: string;
    description: string;
    budget: bigint;
    startDate: _Time;
    milestones: Array<_Milestone>;
    managerName: string;
} {
    return {
        id: value.id,
        status: to_candid_ProjectStatus_n11(_uploadFile, _downloadFile, value.status),
        assignedResourceIds: value.assignedResourceIds,
        endDate: value.endDate,
        name: value.name,
        description: value.description,
        budget: value.budget,
        startDate: value.startDate,
        milestones: value.milestones,
        managerName: value.managerName
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    doj: Time;
    status: ResourceStatus;
    client: string;
    assignmentStartDate: Time;
    totalExperience: string;
    name: string;
    role: string;
    skillTags: Array<string>;
    projectManager: string;
    deliveryHead: string;
    assignmentEndDate: Time;
    email: string;
    employeeId: string;
    projectId?: string;
    practice: string;
    primarySkills: Array<string>;
    billabilityStatus: BillabilityStatus;
    contactNumber: string;
    department: string;
    secondarySkills: Array<string>;
    location: string;
    nonBillableStatus?: NonBillableStatus;
    project: string;
    reportingManager: string;
}): {
    id: string;
    doj: _Time;
    status: _ResourceStatus;
    client: string;
    assignmentStartDate: _Time;
    totalExperience: string;
    name: string;
    role: string;
    skillTags: Array<string>;
    projectManager: string;
    deliveryHead: string;
    assignmentEndDate: _Time;
    email: string;
    employeeId: string;
    projectId: [] | [string];
    practice: string;
    primarySkills: Array<string>;
    billabilityStatus: _BillabilityStatus;
    contactNumber: string;
    department: string;
    secondarySkills: Array<string>;
    location: string;
    nonBillableStatus: [] | [_NonBillableStatus];
    project: string;
    reportingManager: string;
} {
    return {
        id: value.id,
        doj: value.doj,
        status: to_candid_ResourceStatus_n16(_uploadFile, _downloadFile, value.status),
        client: value.client,
        assignmentStartDate: value.assignmentStartDate,
        totalExperience: value.totalExperience,
        name: value.name,
        role: value.role,
        skillTags: value.skillTags,
        projectManager: value.projectManager,
        deliveryHead: value.deliveryHead,
        assignmentEndDate: value.assignmentEndDate,
        email: value.email,
        employeeId: value.employeeId,
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        practice: value.practice,
        primarySkills: value.primarySkills,
        billabilityStatus: to_candid_BillabilityStatus_n18(_uploadFile, _downloadFile, value.billabilityStatus),
        contactNumber: value.contactNumber,
        department: value.department,
        secondarySkills: value.secondarySkills,
        location: value.location,
        nonBillableStatus: value.nonBillableStatus ? candid_some(to_candid_NonBillableStatus_n20(_uploadFile, _downloadFile, value.nonBillableStatus)) : candid_none(),
        project: value.project,
        reportingManager: value.reportingManager
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: UserRole;
    name: string;
}): {
    appRole: _UserRole;
    name: string;
} {
    return {
        appRole: to_candid_UserRole_n57(_uploadFile, _downloadFile, value.appRole),
        name: value.name
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    active: null;
} | {
    completed: null;
} | {
    onHold: null;
} | {
    planning: null;
} {
    return value == ProjectStatus.active ? {
        active: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.onHold ? {
        onHold: null
    } : value == ProjectStatus.planning ? {
        planning: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == ResourceStatus.active ? {
        active: null
    } : value == ResourceStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillabilityStatus): {
    billable: null;
} | {
    nonBillable: null;
} {
    return value == BillabilityStatus.billable ? {
        billable: null
    } : value == BillabilityStatus.nonBillable ? {
        nonBillable: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NonBillableStatus): {
    availableForDeployment: null;
} | {
    solutionInvestment: null;
} | {
    biBench: null;
} | {
    partialBench: null;
} | {
    projectBuffer: null;
} | {
    benchBlocked: null;
} | {
    maternity: null;
} | {
    deliverySupport: null;
} {
    return value == NonBillableStatus.availableForDeployment ? {
        availableForDeployment: null
    } : value == NonBillableStatus.solutionInvestment ? {
        solutionInvestment: null
    } : value == NonBillableStatus.biBench ? {
        biBench: null
    } : value == NonBillableStatus.partialBench ? {
        partialBench: null
    } : value == NonBillableStatus.projectBuffer ? {
        projectBuffer: null
    } : value == NonBillableStatus.benchBlocked ? {
        benchBlocked: null
    } : value == NonBillableStatus.maternity ? {
        maternity: null
    } : value == NonBillableStatus.deliverySupport ? {
        deliverySupport: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    pm: null;
} | {
    pmo: null;
} | {
    admin: null;
} | {
    deliveryHead: null;
} | {
    employee: null;
} | {
    management: null;
} {
    return value == UserRole.pm ? {
        pm: null
    } : value == UserRole.pmo ? {
        pmo: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.deliveryHead ? {
        deliveryHead: null
    } : value == UserRole.employee ? {
        employee: null
    } : value == UserRole.management ? {
        management: null
    } : value;
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Resource>): Array<_Resource> {
    return value.map((x)=>to_candid_Resource_n14(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Project>): Array<_Project> {
    return value.map((x)=>to_candid_Project_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
