/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProjectStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'onHold' : IDL.Null,
  'planning' : IDL.Null,
});
export const Time = IDL.Int;
export const Milestone = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : Time,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'status' : ProjectStatus,
  'assignedResourceIds' : IDL.Vec(IDL.Text),
  'endDate' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'budget' : IDL.Nat,
  'startDate' : Time,
  'milestones' : IDL.Vec(Milestone),
  'managerName' : IDL.Text,
});
export const ResourceStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const BillabilityStatus = IDL.Variant({
  'billable' : IDL.Null,
  'nonBillable' : IDL.Null,
});
export const NonBillableStatus = IDL.Variant({
  'availableForDeployment' : IDL.Null,
  'solutionInvestment' : IDL.Null,
  'biBench' : IDL.Null,
  'partialBench' : IDL.Null,
  'projectBuffer' : IDL.Null,
  'benchBlocked' : IDL.Null,
  'maternity' : IDL.Null,
  'deliverySupport' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Text,
  'doj' : Time,
  'status' : ResourceStatus,
  'client' : IDL.Text,
  'assignmentStartDate' : Time,
  'totalExperience' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'skillTags' : IDL.Vec(IDL.Text),
  'projectManager' : IDL.Text,
  'deliveryHead' : IDL.Text,
  'assignmentEndDate' : Time,
  'email' : IDL.Text,
  'employeeId' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Text),
  'practice' : IDL.Text,
  'primarySkills' : IDL.Vec(IDL.Text),
  'billabilityStatus' : BillabilityStatus,
  'contactNumber' : IDL.Text,
  'department' : IDL.Text,
  'secondarySkills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'nonBillableStatus' : IDL.Opt(NonBillableStatus),
  'project' : IDL.Text,
  'reportingManager' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'pm' : IDL.Null,
  'pmo' : IDL.Null,
  'admin' : IDL.Null,
  'deliveryHead' : IDL.Null,
  'employee' : IDL.Null,
  'management' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : UserRole,
  'name' : IDL.Text,
});
export const TimesheetStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'draft' : IDL.Null,
});
export const TimesheetEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : TimesheetStatus,
  'resourceId' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'projectId' : IDL.Text,
  'hoursLogged' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBulkProjects' : IDL.Func([IDL.Vec(Project)], [], []),
  'addBulkResources' : IDL.Func([IDL.Vec(Resource)], [], []),
  'addProject' : IDL.Func([Project], [], []),
  'addResource' : IDL.Func([Resource], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getPowerBIEmbedUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getProjects' : IDL.Func(
      [IDL.Opt(ProjectStatus), IDL.Opt(IDL.Text), IDL.Opt(Time), IDL.Opt(Time)],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getTimesheetEntries' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Time), IDL.Opt(Time)],
      [IDL.Vec(TimesheetEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPowerBIEmbedUrl' : IDL.Func([IDL.Text], [], []),
  'updateProject' : IDL.Func([Project], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProjectStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'onHold' : IDL.Null,
    'planning' : IDL.Null,
  });
  const Time = IDL.Int;
  const Milestone = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : Time,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'status' : ProjectStatus,
    'assignedResourceIds' : IDL.Vec(IDL.Text),
    'endDate' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'budget' : IDL.Nat,
    'startDate' : Time,
    'milestones' : IDL.Vec(Milestone),
    'managerName' : IDL.Text,
  });
  const ResourceStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const BillabilityStatus = IDL.Variant({
    'billable' : IDL.Null,
    'nonBillable' : IDL.Null,
  });
  const NonBillableStatus = IDL.Variant({
    'availableForDeployment' : IDL.Null,
    'solutionInvestment' : IDL.Null,
    'biBench' : IDL.Null,
    'partialBench' : IDL.Null,
    'projectBuffer' : IDL.Null,
    'benchBlocked' : IDL.Null,
    'maternity' : IDL.Null,
    'deliverySupport' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Text,
    'doj' : Time,
    'status' : ResourceStatus,
    'client' : IDL.Text,
    'assignmentStartDate' : Time,
    'totalExperience' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'skillTags' : IDL.Vec(IDL.Text),
    'projectManager' : IDL.Text,
    'deliveryHead' : IDL.Text,
    'assignmentEndDate' : Time,
    'email' : IDL.Text,
    'employeeId' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Text),
    'practice' : IDL.Text,
    'primarySkills' : IDL.Vec(IDL.Text),
    'billabilityStatus' : BillabilityStatus,
    'contactNumber' : IDL.Text,
    'department' : IDL.Text,
    'secondarySkills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'nonBillableStatus' : IDL.Opt(NonBillableStatus),
    'project' : IDL.Text,
    'reportingManager' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'pm' : IDL.Null,
    'pmo' : IDL.Null,
    'admin' : IDL.Null,
    'deliveryHead' : IDL.Null,
    'employee' : IDL.Null,
    'management' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'appRole' : UserRole, 'name' : IDL.Text });
  const TimesheetStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'draft' : IDL.Null,
  });
  const TimesheetEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : TimesheetStatus,
    'resourceId' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'projectId' : IDL.Text,
    'hoursLogged' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBulkProjects' : IDL.Func([IDL.Vec(Project)], [], []),
    'addBulkResources' : IDL.Func([IDL.Vec(Resource)], [], []),
    'addProject' : IDL.Func([Project], [], []),
    'addResource' : IDL.Func([Resource], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getPowerBIEmbedUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getProjects' : IDL.Func(
        [
          IDL.Opt(ProjectStatus),
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(Time),
        ],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getTimesheetEntries' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Time), IDL.Opt(Time)],
        [IDL.Vec(TimesheetEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPowerBIEmbedUrl' : IDL.Func([IDL.Text], [], []),
    'updateProject' : IDL.Func([Project], [], []),
  });
};

export const init = ({ IDL }) => { return []; };