/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BillabilityStatus = { 'billable' : null } |
  { 'nonBillable' : null };
export interface Milestone {
  'id' : string,
  'title' : string,
  'completed' : boolean,
  'dueDate' : Time,
}
export type NonBillableStatus = { 'availableForDeployment' : null } |
  { 'solutionInvestment' : null } |
  { 'biBench' : null } |
  { 'partialBench' : null } |
  { 'projectBuffer' : null } |
  { 'benchBlocked' : null } |
  { 'maternity' : null } |
  { 'deliverySupport' : null };
export interface Project {
  'id' : string,
  'status' : ProjectStatus,
  'assignedResourceIds' : Array<string>,
  'endDate' : Time,
  'name' : string,
  'description' : string,
  'budget' : bigint,
  'startDate' : Time,
  'milestones' : Array<Milestone>,
  'managerName' : string,
}
export type ProjectStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'onHold' : null } |
  { 'planning' : null };
export interface Resource {
  'id' : string,
  'doj' : Time,
  'status' : ResourceStatus,
  'client' : string,
  'assignmentStartDate' : Time,
  'totalExperience' : string,
  'name' : string,
  'role' : string,
  'skillTags' : Array<string>,
  'projectManager' : string,
  'deliveryHead' : string,
  'assignmentEndDate' : Time,
  'email' : string,
  'employeeId' : string,
  'projectId' : [] | [string],
  'practice' : string,
  'primarySkills' : Array<string>,
  'billabilityStatus' : BillabilityStatus,
  'contactNumber' : string,
  'department' : string,
  'secondarySkills' : Array<string>,
  'location' : string,
  'nonBillableStatus' : [] | [NonBillableStatus],
  'project' : string,
  'reportingManager' : string,
}
export type ResourceStatus = { 'active' : null } |
  { 'inactive' : null };
export type Time = bigint;
export interface TimesheetEntry {
  'id' : string,
  'status' : TimesheetStatus,
  'resourceId' : string,
  'date' : Time,
  'description' : string,
  'projectId' : string,
  'hoursLogged' : bigint,
}
export type TimesheetStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'draft' : null };
export interface UserProfile { 'appRole' : UserRole, 'name' : string }
export type UserRole = { 'pm' : null } |
  { 'pmo' : null } |
  { 'admin' : null } |
  { 'deliveryHead' : null } |
  { 'employee' : null } |
  { 'management' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Bulk-add projects. Permitted for admins and PMO users.
   */
  'addBulkProjects' : ActorMethod<[Array<Project>], undefined>,
  /**
   * / Bulk-add resources. Permitted for admins and PMO users.
   */
  'addBulkResources' : ActorMethod<[Array<Resource>], undefined>,
  /**
   * / Create a new project. Permitted for admins and PMO users.
   */
  'addProject' : ActorMethod<[Project], undefined>,
  /**
   * / Add a single resource. Permitted for admins and PMO users.
   */
  'addResource' : ActorMethod<[Resource], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  /**
   * / **************** Power BI Reporting ************
   */
  'getPowerBIEmbedUrl' : ActorMethod<[], [] | [string]>,
  /**
   * / **************** Projects **********************
   */
  'getProjects' : ActorMethod<
    [[] | [ProjectStatus], [] | [string], [] | [Time], [] | [Time]],
    Array<Project>
  >,
  /**
   * / **************** Resource Management ********************
   */
  'getResources' : ActorMethod<[], Array<Resource>>,
  /**
   * / **************** Timesheets *******************
   */
  'getTimesheetEntries' : ActorMethod<
    [[] | [string], [] | [string], [] | [Time], [] | [Time]],
    Array<TimesheetEntry>
  >,
  /**
   * / **************** User Profiles *****************
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPowerBIEmbedUrl' : ActorMethod<[string], undefined>,
  /**
   * / Update an existing project. Permitted for admins and PMO users.
   */
  'updateProject' : ActorMethod<[Project], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];